# Default plugin config
back-button:
  manual-open-command: "cp rezepte {player}"
# this command executes if the player opens the crafting menu for a specific
# minion type via command and presses the "back" button. leave empty if you just want the menu to close.
# you could use this to direct a player to another GUI that has been made by a different plugin.